import io
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

def generate_patient_pdf(patient_data: dict, interventions: list) -> io.BytesIO:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=18)
    
    styles = getSampleStyleSheet()
    title_style = styles['Heading1']
    title_style.alignment = 1 # Center
    
    h2_style = styles['Heading2']
    normal_style = styles['Normal']
    
    elements = []
    
    # Title
    elements.append(Paragraph("LMSIS Metabolic State Report", title_style))
    elements.append(Spacer(1, 24))
    
    # Patient Summary
    elements.append(Paragraph("Patient Clinical Summary", h2_style))
    elements.append(Spacer(1, 12))
    
    summary_data = [
        ["Phenotype", patient_data.get('quadrant_name', 'Unknown')],
        ["Predicted HOMA-IR", f"{patient_data.get('pred_homa_ir', 0):.2f}"],
        ["Predicted Liver Fat (CAP)", f"{patient_data.get('pred_cap', 0):.0f} dB/m"],
        ["Risk Score", f"{patient_data.get('risk_score', 0):.3f}"],
    ]
    
    t = Table(summary_data, colWidths=[200, 200])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.lightgrey),
        ('TEXTCOLOR', (0,0), (-1,-1), colors.black),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 12),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ('TOPPADDING', (0,0), (-1,-1), 8),
        ('GRID', (0,0), (-1,-1), 1, colors.black)
    ]))
    
    elements.append(t)
    elements.append(Spacer(1, 24))
    
    # Interventions
    if interventions:
        elements.append(Paragraph("Recommended Targeted Interventions", h2_style))
        elements.append(Spacer(1, 12))
        
        interv_data = [["Biomarker Target", "Current Value", "Target Value", "Required Shift"]]
        for inv in interventions:
            interv_data.append([
                inv.get('name', ''),
                f"{inv.get('current', 0):.1f} {inv.get('unit', '')}",
                f"{inv.get('target', 0):.1f} {inv.get('unit', '')}",
                f"{inv.get('diff', 0):.1f} {inv.get('unit', '')}"
            ])
            
        t2 = Table(interv_data, colWidths=[120, 100, 100, 100])
        t2.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#4A6380')),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('FONTSIZE', (0,0), (-1,-1), 10),
            ('BOTTOMPADDING', (0,0), (-1,-1), 8),
            ('TOPPADDING', (0,0), (-1,-1), 8),
            ('GRID', (0,0), (-1,-1), 0.5, colors.grey)
        ]))
        elements.append(t2)
    else:
        elements.append(Paragraph("Patient is in the Metabolically Healthy Normal Weight (MHNW) zone. No primary interventions required.", normal_style))
    
    elements.append(Spacer(1, 48))
    elements.append(Paragraph("Generated by the Latent Metabolic State Inference System (LMSIS)", styles['Italic']))
    
    doc.build(elements)
    buffer.seek(0)
    return buffer
